stages:
  - build

before_script:
  - apt-get update -qq && apt-get install -y mingw32
  - export GRADLE_USER_HOME=`pwd`/.gradle

build-native:
  stage: build
  image: gcc:7.2.0
  script:
    - "cd native/xenon-server"
    - "make && make windows-i686 && make windows-x86_64"
    - "cd ../.."
  artifacts:
    paths:
      - native/xenon-server/*.dll
      - native/xenon-server/*.so

build-java:
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  image: java:8-jdk
  stage: build
  script:
    - "./gradlew assemble"
    - "./gradlew :xenon-api:build"
  artifacts:
    paths:
      - xenon-api/build/libs/*.jar