stages:
  - build

build-native:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y gcc mingw32
  script:
    - "cd native/xenon-server"
    - "make && make windows-i686 && make windows-x86_64"
    - "cd ../.."
  artifacts:
    paths:
      - native/xenon-server/*.dll
      - native/xenon-server/*.so

build-java:
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  image: java:8-jdk
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - "./gradlew assemble"
  artifacts:
    paths:
      - xenon-api/build/libs/*.jar