stages:
  - build

build-native:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y gcc mingw32
  script:
    - "mkdir deploy"
    - "cd native/xenon-server"
    - "make && make windows-i686 && make windows-x86_64"
    - "mv *.dll ../../deploy/ && mv *.so ../../deploy"
    - "cd ../.."
  artifacts:
    name: "xenon-minecraft-natives"
    paths:
      - deploy/*.*

build-java:
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  image: java:8-jdk
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - "mkdir deploy"
    - "./gradlew :xenon-api:build"
    - "mv xenon-api/build/libs/*.jar deploy/"
  artifacts:
    name: "xenon-minecraft"
    paths:
      - deploy/*.*