stages:
  - build

build-java:
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  image: java:8-jdk
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - "mkdir deploy"
    - "./gradlew :xenon-server:fatJar"
    - "mv xenon-server/build/libs/*.jar deploy/"
  artifacts:
    name: "xenon-minecraft"
    paths:
      - deploy/*.*