language: java
sudo: required
before_install:
- sudo apt-get -qq update
install:
- "./gradlew assemble"
script:
- cd ./native/xenon-server
- make && make windows-i686 && make windows-x86_64
- cd ../..
- "./gradlew :xenon-api:build"
before_deploy:
- git config --local user.name "SebastianAgius"
- git config --local user.email "theultimatepleb@gmail.com"
deploy:
  provider: releases
  file_glob: true
  file:
    - "xenon-api/build/libs/*"
    - "native/xenon-server/*"
  api_key:
    secure: secure: "OMCewatCpU5HPXkOVdWoK8BouLZzPk1k2fDBLbrJuJ3ja7p23QtHLLNSyg4OvUpKGdkleJ/Ivy4nYMUYYj9Flg7hiRzyy/uCsolGoJN1IzFrLm7R6HGQcjKCz5si93HUatGsr2A+yZj2RGeCwVFScSvZD5cGZ4ROXTpQB77HuruKpbu4gISUf3fgkfNQKCxfLVqLEzP5eJbFYMqNYbe/rEnOZFsMRrCImfq7oFudxfu9rHBSd03bKeBNcxpwCJVR7c1pPSw4ycGX38pnXvHck++zN6f8jlOideh2Bkd6tcbRiusTMNjZFUKoW/u4IpEK2j7uqeULSiVyobX2bEfUoiXC07gRkKZxw+Spz0fcRbDcu4Xg+qnjLHs6n1g8hpMkg+6/xoT74gbjn00dG4H7KBvkL7q70xYpQyu4zJgq2GJqt9CyjXdQcxqo+1o2NORX0pcWecQxkcyM/dmQ7bIXQe8Ets4A87kqWniqt5OBlBjJN0oJ7vvWbpqUUqe2pTvR4zK81A3kwWLi7XZsWHH93xQu1fUonpow58NXs78QBZ7W1Qtw60SQRsUh7un8q1uh8MTG/Ld/C/AsPHX8kyIiLf6iY5V1LmkkXKnMpZLWNG2EwaJZh5v68QJCfUs0Z6TOoD5oRAG32SSmO/fZQPax5LQybyltQdLH1cOo6a1dYDs="